main:
  - name: Recherche
    url: research
    weight: 10
  - name: Équipe
    url: people
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: Actualités
    url: post
    weight: 40
  - name: Postes
    url: open-positions
    weight: 50
  - name: Participer
    url: participate
    weight: 60
